#ifndef _ERROR_H
#define _ERROR_H

#define NOT_VALID_INSTRUCTION 10
#define NOT_VALID_OPERATOR  20
#define NOT_VALID_OPERAND 30
#define LIMIT_EXCEEDED 40
#define ERR_SYNTAX  50
#define NOT_VALID_OPREANDINFO_TYPE 60
#define EXTRA_OPERAND 70
#endif // _ERROR_H
