#ifndef _ERROR_H
#define _ERROR_H

#define NOT_VALID_INSTRUCTION 45
#define NOT_VALID_OPERATOR  46
#define NOT_VALID_OPERAND 47
#define EXTRA_OPERAND 48
#define LIMIT_EXCEEDED 49
#define ERR_SYNTAX  50
#endif // _ERROR_H
